language: c

env:
  global:
    # C flags
    - CFLAGS="-c -Wall"
    # Misc
    - RUN_TESTS=true
jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
      language: shell
      addons:
        homebrew:
          packages:
            - cmake
          update: true
script:
  - bash ./compile.sh
  - ls test