language: c

env:
  global:
    # C flags
    - CFLAGS="-c -Wall"
    # Misc
    - RUN_TESTS=true
matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
      language: shell
      addons:
        homebrew:
          packages:
            - cmake
          update: true
before_install:
  - mkdir -p "$HOME"/Deps "$HOME"/Dowloads
install:
  - echo "-- Installing CMake"
  - hdiutil attach cmake-3.17.0-rc2-Darwin-x86_64.dmg
  - cp -Rf /Volumes/cmake-3.17.0-rc2-Darwin-x86_64/CMake.app /Applications/
  - hdiutil detach /Volumes/cmake-3.8.1-Darwin-x86_64
  - /Applications/CMake.app/Contents/bin/cmake-gui --install
  - echo "-- Done installing CMake"
script:
  - bash ./compiler.sh


