language: c
sudo: false

env:
  global:
    # C flags
    - CFLAGS="-c -Wall"
    # Misc
    - RUN_TESTS=true
matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
      language: shell
      addons:
        homebrew:
          packages:
            - cmake
          update: true
before_install:
  - mkdir -p "$HOME"/Deps "$HOME"/Dowloads
script:
  - bash ./compiler.sh


