language: c

env:
  global:
    # C flags
    - CFLAGS="-c -Wall"
    # Misc
    - RUN_TESTS=true
jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
      language: shell
install:
  - echo "-- Installing CMake"
  - curl https://cmake.org/files/v3.17/cmake-3.17.0-rc2-Darwin-x86_64.tar.gz -O
  - tar -xzf cmake-3.17.0-rc2-Darwin-x86_64.tar.gz
  - mv cmake-3.17.0-rc2-Darwin-x86_64/CMake.app /Applications
  - /Applications/CMake.app/Contents/bin/cmake-gui --install
  - echo "-- Done installing CMake"
script:
  - bash ./compiler.sh


